- name: SonarCloud Scan
  uses: SonarSource/sonarqube-scan-action@v5
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_HOST_URL: http://localhost:9000
  with:
    args: >
      -Dsonar.projectKey=ToDoList
      -Dsonar.organization=VynicyusCandido
      -Dsonar.sources=src
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info